const express = require('express');
const { getPosts, getPostById, createPost, updatePost, deletePost } = require('../controllers/postController');
const router = express.Router();

router.get('/', getPosts); //Get all  posts....
router.get('/:id', getPostById); //Get a single post...
router.post('/', createPost); //Create a new post....
router.put('/:id', updatePost);  //update a post....
router.delete('/:id', deletePost); //delete a post

module.exports = router;